apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: student-j-donnerbauer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: student.cloud.htl-leonding.ac.at
    http:
      paths:
        - backend:
            service:
              name: keycloak-service
              port:
                number: 80
          path: /j.donnerbauer/auth(/|$)(.*)$
          pathType: Prefix