apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: student-j-donnerbauer
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer