version: '3.5'

services:
  db_keycloak:
    image: mysql:5.7
    volumes:
      - mysql_keycloak:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
     - 3306:3306

  db_connect:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connect
      MYSQL_USER: connect
      MYSQL_PASSWORD: password
    ports:
     - 3307:3306


  keycloak:
      build:
        context: .
        dockerfile: Dockerfile_local
      ports:
        - 8010:8080
      volumes:
        - keycloak_data:/var/lib/keycloak/data
        - ./realm/cache/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
        - ./realm/properties/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
        - ./realm/theme/login.ftl:/opt/jboss/keycloak/themes/base/login/login.ftl
        - ./realm/theme/register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl
        - ./realm/theme/template.ftl:/opt/jboss/keycloak/themes/base/login/template.ftl
        - ./realm/theme/login.css:/opt/jboss/keycloak/themes/custom/login/resources/css/login.css
        - ./realm/theme/Connect_Logo_Positv_Negativ.png:/opt/jboss/keycloak/themes/custom/login/resources/img/Connect_Logo_Positv_Negativ.png
      depends_on:
        - db_keycloak

volumes:
  mysql_keycloak:
  mysql_data:
  keycloak_data: