version: '3.5'

volumes:
  mysql_data:
  keycloak_data:

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password

  keycloak:
      image: jboss/keycloak
      environment:
#        KEYCLOAK_IMPORT: /opt/jboss/keycloak/realm-config/realm.json
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_STATISTICS: all
      ports:
        - 8010:8080
      volumes:
        - keycloak_data:/var/lib/keycloak/data
        - ./realm:/opt/jboss/keycloak/realm-config
      depends_on:
        - mysql